2013/01/07 22:25:24 [error] [exception.CException] exception 'CException' with message 'El asset "C:\xampp\htdocs\sgt\protected/vendors/jqueryui/ThemeSGT/ a ser publicado no existe.' in C:\xampp\htdocs\yii\framework\web\CAssetManager.php:257
Stack trace:
#0 C:\xampp\htdocs\sgt\protected\views\layouts\main.php(19): CAssetManager->publish('C:\xampp\htdocs...')
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#8 C:\xampp\htdocs\sgt\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(32): CController->render('index')
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sgt/index.php/site/index
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/07 22:26:40 [error] [exception.CException] exception 'CException' with message 'El asset "C:\xampp\htdocs\sgt\protected\vendors\jqueryui\ThemeSGT a ser publicado no existe.' in C:\xampp\htdocs\yii\framework\web\CAssetManager.php:257
Stack trace:
#0 C:\xampp\htdocs\sgt\protected\views\layouts\main.php(19): CAssetManager->publish('C:\xampp\htdocs...')
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#8 C:\xampp\htdocs\sgt\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(32): CController->render('index')
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sgt/index.php/site/index
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/07 22:28:51 [error] [exception.CException] exception 'CException' with message 'El asset "C:\xampp\htdocs\sgt\protected\vendors\jqueryui\ThemeSGT\  a ser publicado no existe.' in C:\xampp\htdocs\yii\framework\web\CAssetManager.php:257
Stack trace:
#0 C:\xampp\htdocs\sgt\protected\views\layouts\main.php(19): CAssetManager->publish('C:\xampp\htdocs...')
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#8 C:\xampp\htdocs\sgt\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(32): CController->render('index')
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sgt/index.php/site/index
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/07 22:29:25 [error] [exception.CException] exception 'CException' with message 'El asset "C:\xampp\htdocs\sgt\protected\vendors\jquery.ui\ThemeSGT\  a ser publicado no existe.' in C:\xampp\htdocs\yii\framework\web\CAssetManager.php:257
Stack trace:
#0 C:\xampp\htdocs\sgt\protected\views\layouts\main.php(19): CAssetManager->publish('C:\xampp\htdocs...')
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#8 C:\xampp\htdocs\sgt\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(32): CController->render('index')
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sgt/index.php/site/index
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/07 22:29:42 [error] [exception.CException] exception 'CException' with message 'El asset "C:\xampp\htdocs\sgt\protected/vendors/jquery.ui/ThemeSGT/ a ser publicado no existe.' in C:\xampp\htdocs\yii\framework\web\CAssetManager.php:257
Stack trace:
#0 C:\xampp\htdocs\sgt\protected\views\layouts\main.php(19): CAssetManager->publish('C:\xampp\htdocs...')
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#8 C:\xampp\htdocs\sgt\protected\views\layouts\column1.php(6): CBaseController->endContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(32): CController->render('index')
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sgt/index.php/site/index
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:39:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:39:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:39:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:39:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:39:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:39:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:40:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "images" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/tal...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/taller/taller2.jpg"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/taller/t...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/taller/taller.jpg"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/taller/t...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/taller/taller3.jpg"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/taller/t...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/taller/taller3.jpg"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/taller/t...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/images/taller/taller3.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/taller/taller.jpg"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/taller/t...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/images/taller/taller.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "images/taller/taller2.jpg"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/taller/t...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/images/taller/taller2.jpg
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:52:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:56:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:56:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:56:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:56:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:57:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "consulta" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('consulta')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('consulta')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ordenes/consult...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/ordenes/consulta
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:57:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:57:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:57:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/close....')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/close.png
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/08 23:57:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "img" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('img')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('img')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/img/loadin...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/img/loading.gif
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/09 00:09:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "consulta" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('consulta')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('consulta')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ordenes/consult...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/ordenes/consulta
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/09 00:11:31 [error] [php] mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\sgt\protected\controllers\SiteController.php:67)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 C:\xampp\htdocs\sgt\index.php(13): CWebApplication->run()
REQUEST_URI=/sgt/index.php/site/contact
in C:\xampp\htdocs\sgt\protected\controllers\SiteController.php (67)
in C:\xampp\htdocs\sgt\index.php (13)
2013/01/09 01:08:57 [error] [php] Undefined variable: model (C:\xampp\htdocs\sgt\protected\components\UserIdentity.php:20)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CWebApplication->run()
REQUEST_URI=/sgt/index.php/site/login
in C:\xampp\htdocs\sgt\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\sgt\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\sgt\protected\controllers\SiteController.php (94)
2013/01/09 01:10:15 [error] [php] Undefined variable: model (C:\xampp\htdocs\sgt\protected\components\UserIdentity.php:23)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CWebApplication->run()
REQUEST_URI=/sgt/index.php/site/login
in C:\xampp\htdocs\sgt\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\sgt\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\sgt\protected\controllers\SiteController.php (94)
2013/01/09 01:11:01 [error] [php] Undefined variable: model (C:\xampp\htdocs\sgt\protected\components\UserIdentity.php:23)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CWebApplication->run()
REQUEST_URI=/sgt/index.php/site/login
in C:\xampp\htdocs\sgt\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\sgt\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\sgt\protected\controllers\SiteController.php (94)
2013/01/09 01:14:26 [error] [php] Undefined variable: model (C:\xampp\htdocs\sgt\protected\components\UserIdentity.php:23)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CWebApplication->run()
REQUEST_URI=/sgt/index.php/site/login
in C:\xampp\htdocs\sgt\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\sgt\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\sgt\protected\controllers\SiteController.php (94)
2013/01/09 01:16:31 [error] [php] Undefined variable: model (C:\xampp\htdocs\sgt\protected\components\UserIdentity.php:24)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\sgt\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CWebApplication->run()
REQUEST_URI=/sgt/index.php/site/login
in C:\xampp\htdocs\sgt\protected\components\UserIdentity.php (24)
in C:\xampp\htdocs\sgt\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\sgt\protected\controllers\SiteController.php (94)
2013/01/09 21:27:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "consulta" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('consulta')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('consulta')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ordenes/consult...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/ordenes/consulta
HTTP_REFERER=http://localhost/sgt/index.php
---
2013/01/09 21:36:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "contacto.php" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contacto.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contacto.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contacto.p...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/site/contacto.php
HTTP_REFERER=http://localhost/sgt/index.php/site/page?view=about
---
2013/01/09 21:58:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "consulta"' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('consulta')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sgt/index.php/consulta
---
2013/01/09 21:58:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('consultas/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/sgt/index.php/consultas/admin
HTTP_REFERER=http://localhost/sgt/index.php/consultas/create
---
2013/01/09 22:33:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('consultas/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/sgt/index.php/consultas/admin
HTTP_REFERER=http://localhost/sgt/index.php/consultas/index
---
2013/01/09 23:40:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "consulta" solicitada.' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('consulta')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('consulta')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ordenes/consult...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sgt\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sgt/index.php/ordenes/consulta
HTTP_REFERER=http://localhost/sgt/index.php
---
